// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Regenerate with: npx tsx scripts/generate-levels.ts
// Every level here was accepted only after src/engine/solver.ts confirmed it is
// winnable (see docs/level-generator.md), except any flagged in that script's
// warning output, which are marked unverified and best treated as provisional.

import type { LevelConfig } from '../engine/types'

export const LEVELS: LevelConfig[] = [
  {
    "id": "daily-life-01",
    "chapterId": "daily-life",
    "difficulty": "easy",
    "categoryIds": [
      "clothing",
      "tool",
      "drink"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "clothing": 4,
      "tool": 4,
      "drink": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "daily-life-01-s0"
  },
  {
    "id": "daily-life-02",
    "chapterId": "daily-life",
    "difficulty": "easy",
    "categoryIds": [
      "color",
      "animal",
      "stationery"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "color": 4,
      "animal": 4,
      "stationery": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "daily-life-02-s0"
  },
  {
    "id": "daily-life-03",
    "chapterId": "daily-life",
    "difficulty": "easy",
    "categoryIds": [
      "furniture",
      "color",
      "stationery"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "furniture": 4,
      "color": 4,
      "stationery": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "daily-life-03-s0"
  },
  {
    "id": "daily-life-04",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "fruit",
      "vehicle",
      "furniture",
      "stationery"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "fruit": 5,
      "vehicle": 5,
      "furniture": 5,
      "stationery": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-04-s0"
  },
  {
    "id": "daily-life-05",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "vehicle",
      "clothing",
      "stationery",
      "animal"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "vehicle": 5,
      "clothing": 5,
      "stationery": 5,
      "animal": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-05-s0"
  },
  {
    "id": "daily-life-06",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "stationery",
      "occupation",
      "clothing",
      "vehicle"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "stationery": 5,
      "occupation": 5,
      "clothing": 5,
      "vehicle": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-06-s1"
  },
  {
    "id": "daily-life-07",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "stationery",
      "appliance",
      "furniture",
      "tool"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "stationery": 5,
      "appliance": 5,
      "furniture": 5,
      "tool": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-07-s0"
  },
  {
    "id": "daily-life-08",
    "chapterId": "daily-life",
    "difficulty": "hard",
    "categoryIds": [
      "animal",
      "clothing",
      "dessert",
      "furniture",
      "occupation"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "animal": 6,
      "clothing": 6,
      "dessert": 6,
      "furniture": 6,
      "occupation": 6
    },
    "targetThreeStarMoves": 46,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "daily-life-08-s0"
  },
  {
    "id": "natural-world-01",
    "chapterId": "natural-world",
    "difficulty": "easy",
    "categoryIds": [
      "insect",
      "flower",
      "scenery"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "insect": 4,
      "flower": 4,
      "scenery": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "natural-world-01-s0"
  },
  {
    "id": "natural-world-02",
    "chapterId": "natural-world",
    "difficulty": "easy",
    "categoryIds": [
      "scenery",
      "weather",
      "bird"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "scenery": 4,
      "weather": 4,
      "bird": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "natural-world-02-s0"
  },
  {
    "id": "natural-world-03",
    "chapterId": "natural-world",
    "difficulty": "normal",
    "categoryIds": [
      "planet",
      "bird",
      "weather",
      "scenery"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "planet": 5,
      "bird": 5,
      "weather": 5,
      "scenery": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "natural-world-03-s0"
  },
  {
    "id": "natural-world-04",
    "chapterId": "natural-world",
    "difficulty": "normal",
    "categoryIds": [
      "weather",
      "insect",
      "bird",
      "scenery"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "weather": 5,
      "insect": 5,
      "bird": 5,
      "scenery": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "natural-world-04-s0"
  },
  {
    "id": "natural-world-05",
    "chapterId": "natural-world",
    "difficulty": "normal",
    "categoryIds": [
      "flower",
      "bird",
      "insect",
      "planet"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "flower": 5,
      "bird": 5,
      "insect": 5,
      "planet": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "natural-world-05-s0"
  },
  {
    "id": "natural-world-06",
    "chapterId": "natural-world",
    "difficulty": "hard",
    "categoryIds": [
      "marine",
      "flower",
      "bird",
      "scenery",
      "weather"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "marine": 6,
      "flower": 6,
      "bird": 6,
      "scenery": 6,
      "weather": 6
    },
    "targetThreeStarMoves": 46,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "natural-world-06-s1"
  },
  {
    "id": "food-culture-01",
    "chapterId": "food-culture",
    "difficulty": "easy",
    "categoryIds": [
      "fruit",
      "dessert",
      "festival"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "fruit": 4,
      "dessert": 4,
      "festival": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "food-culture-01-s0"
  },
  {
    "id": "food-culture-02",
    "chapterId": "food-culture",
    "difficulty": "easy",
    "categoryIds": [
      "festival",
      "drink",
      "dessert"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "festival": 4,
      "drink": 4,
      "dessert": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "food-culture-02-s0"
  },
  {
    "id": "food-culture-03",
    "chapterId": "food-culture",
    "difficulty": "normal",
    "categoryIds": [
      "cuisine",
      "drink",
      "festival",
      "dessert"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "cuisine": 5,
      "drink": 5,
      "festival": 5,
      "dessert": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "food-culture-03-s0"
  },
  {
    "id": "food-culture-04",
    "chapterId": "food-culture",
    "difficulty": "normal",
    "categoryIds": [
      "drink",
      "cuisine",
      "dessert",
      "festival"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "drink": 5,
      "cuisine": 5,
      "dessert": 5,
      "festival": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "food-culture-04-s0"
  },
  {
    "id": "food-culture-05",
    "chapterId": "food-culture",
    "difficulty": "normal",
    "categoryIds": [
      "fruit",
      "drink",
      "dessert",
      "festival"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "fruit": 5,
      "drink": 5,
      "dessert": 5,
      "festival": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "food-culture-05-s0"
  },
  {
    "id": "food-culture-06",
    "chapterId": "food-culture",
    "difficulty": "hard",
    "categoryIds": [
      "cuisine",
      "fruit",
      "festival",
      "drink",
      "dessert"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "cuisine": 6,
      "fruit": 6,
      "festival": 6,
      "drink": 6,
      "dessert": 6
    },
    "targetThreeStarMoves": 46,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "food-culture-06-s2"
  },
  {
    "id": "world-travel-01",
    "chapterId": "world-travel",
    "difficulty": "easy",
    "categoryIds": [
      "country",
      "cuisine",
      "city"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "country": 4,
      "cuisine": 4,
      "city": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "world-travel-01-s0"
  },
  {
    "id": "world-travel-02",
    "chapterId": "world-travel",
    "difficulty": "easy",
    "categoryIds": [
      "sport",
      "cuisine",
      "vehicle"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "sport": 4,
      "cuisine": 4,
      "vehicle": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "world-travel-02-s0"
  },
  {
    "id": "world-travel-03",
    "chapterId": "world-travel",
    "difficulty": "normal",
    "categoryIds": [
      "cuisine",
      "city",
      "vehicle",
      "sport"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "cuisine": 5,
      "city": 5,
      "vehicle": 5,
      "sport": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "world-travel-03-s0"
  },
  {
    "id": "world-travel-04",
    "chapterId": "world-travel",
    "difficulty": "normal",
    "categoryIds": [
      "sport",
      "vehicle",
      "city",
      "country"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "sport": 5,
      "vehicle": 5,
      "city": 5,
      "country": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "world-travel-04-s0"
  },
  {
    "id": "world-travel-05",
    "chapterId": "world-travel",
    "difficulty": "normal",
    "categoryIds": [
      "occupation",
      "country",
      "city",
      "cuisine"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "occupation": 5,
      "country": 5,
      "city": 5,
      "cuisine": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "world-travel-05-s0"
  },
  {
    "id": "world-travel-06",
    "chapterId": "world-travel",
    "difficulty": "hard",
    "categoryIds": [
      "country",
      "occupation",
      "vehicle",
      "cuisine",
      "sport"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "country": 6,
      "occupation": 6,
      "vehicle": 6,
      "cuisine": 6,
      "sport": 6
    },
    "targetThreeStarMoves": 46,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "world-travel-06-s2"
  },
  {
    "id": "arts-entertainment-01",
    "chapterId": "arts-entertainment",
    "difficulty": "easy",
    "categoryIds": [
      "architecture",
      "musicGenre",
      "filmGenre"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "architecture": 4,
      "musicGenre": 4,
      "filmGenre": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "arts-entertainment-01-s0"
  },
  {
    "id": "arts-entertainment-02",
    "chapterId": "arts-entertainment",
    "difficulty": "easy",
    "categoryIds": [
      "instrument",
      "filmGenre",
      "musicGenre"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "instrument": 4,
      "filmGenre": 4,
      "musicGenre": 4
    },
    "targetThreeStarMoves": 20,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "arts-entertainment-02-s0"
  },
  {
    "id": "arts-entertainment-03",
    "chapterId": "arts-entertainment",
    "difficulty": "normal",
    "categoryIds": [
      "filmGenre",
      "instrument",
      "architecture",
      "musicGenre"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "filmGenre": 5,
      "instrument": 5,
      "architecture": 5,
      "musicGenre": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "arts-entertainment-03-s0"
  },
  {
    "id": "arts-entertainment-04",
    "chapterId": "arts-entertainment",
    "difficulty": "normal",
    "categoryIds": [
      "musicGenre",
      "instrument",
      "architecture",
      "filmGenre"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 6,
    "categoryWordCounts": {
      "musicGenre": 5,
      "instrument": 5,
      "architecture": 5,
      "filmGenre": 5
    },
    "targetThreeStarMoves": 31,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "arts-entertainment-04-s0"
  }
]
