// AUTO-GENERATED by scripts/generate-levels.ts — do not hand-edit.
// Regenerate with: npx tsx scripts/generate-levels.ts
// Every level here was accepted only after src/engine/solver.ts confirmed it is
// winnable (see docs/level-generator.md), except any flagged in that script's
// warning output, which are marked unverified and best treated as provisional.

import type { LevelConfig } from '../engine/types'

export const LEVELS: LevelConfig[] = [
  {
    "id": "daily-life-01",
    "chapterId": "daily-life",
    "difficulty": "easy",
    "categoryIds": [
      "clothing",
      "tool",
      "drink"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "clothing": 3,
      "tool": 5,
      "drink": 4
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "daily-life-01-s0"
  },
  {
    "id": "daily-life-02",
    "chapterId": "daily-life",
    "difficulty": "easy",
    "categoryIds": [
      "occupation",
      "animal",
      "color"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "occupation": 4,
      "animal": 5,
      "color": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "daily-life-02-s0"
  },
  {
    "id": "daily-life-03",
    "chapterId": "daily-life",
    "difficulty": "easy",
    "categoryIds": [
      "occupation",
      "furniture",
      "stationery"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "occupation": 4,
      "furniture": 3,
      "stationery": 5
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "daily-life-03-s0"
  },
  {
    "id": "daily-life-04",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "fruit",
      "occupation",
      "vehicle",
      "animal"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "fruit": 4,
      "occupation": 6,
      "vehicle": 4,
      "animal": 6
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-04-s0"
  },
  {
    "id": "daily-life-05",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "dessert",
      "occupation",
      "animal",
      "stationery"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "dessert": 6,
      "occupation": 6,
      "animal": 4,
      "stationery": 4
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-05-s0"
  },
  {
    "id": "daily-life-06",
    "chapterId": "daily-life",
    "difficulty": "normal",
    "categoryIds": [
      "dessert",
      "occupation",
      "color",
      "appliance"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "dessert": 4,
      "occupation": 6,
      "color": 6,
      "appliance": 4
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "daily-life-06-s1"
  },
  {
    "id": "daily-life-07",
    "chapterId": "daily-life",
    "difficulty": "hard",
    "categoryIds": [
      "appliance",
      "vehicle",
      "occupation",
      "stationery",
      "dessert"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "appliance": 6,
      "vehicle": 7,
      "occupation": 5,
      "stationery": 5,
      "dessert": 7
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "daily-life-07-s3"
  },
  {
    "id": "daily-life-08",
    "chapterId": "daily-life",
    "difficulty": "hard",
    "categoryIds": [
      "stationery",
      "color",
      "fruit",
      "vehicle",
      "tool"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "stationery": 5,
      "color": 7,
      "fruit": 7,
      "vehicle": 6,
      "tool": 5
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "daily-life-08-s0"
  },
  {
    "id": "natural-world-01",
    "chapterId": "natural-world",
    "difficulty": "easy",
    "categoryIds": [
      "insect",
      "flower",
      "scenery"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "insect": 4,
      "flower": 5,
      "scenery": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "natural-world-01-s0"
  },
  {
    "id": "natural-world-02",
    "chapterId": "natural-world",
    "difficulty": "easy",
    "categoryIds": [
      "insect",
      "planet",
      "scenery"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "insect": 5,
      "planet": 4,
      "scenery": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "natural-world-02-s0"
  },
  {
    "id": "natural-world-03",
    "chapterId": "natural-world",
    "difficulty": "normal",
    "categoryIds": [
      "bird",
      "marine",
      "scenery",
      "insect"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "bird": 6,
      "marine": 4,
      "scenery": 4,
      "insect": 6
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "natural-world-03-s0"
  },
  {
    "id": "natural-world-04",
    "chapterId": "natural-world",
    "difficulty": "normal",
    "categoryIds": [
      "marine",
      "insect",
      "bird",
      "flower"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "marine": 4,
      "insect": 6,
      "bird": 4,
      "flower": 6
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "natural-world-04-s0"
  },
  {
    "id": "natural-world-05",
    "chapterId": "natural-world",
    "difficulty": "hard",
    "categoryIds": [
      "scenery",
      "insect",
      "marine",
      "weather",
      "planet"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "scenery": 5,
      "insect": 6,
      "marine": 5,
      "weather": 7,
      "planet": 7
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "natural-world-05-s0"
  },
  {
    "id": "natural-world-06",
    "chapterId": "natural-world",
    "difficulty": "hard",
    "categoryIds": [
      "scenery",
      "insect",
      "bird",
      "flower",
      "weather"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "scenery": 7,
      "insect": 7,
      "bird": 6,
      "flower": 5,
      "weather": 5
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "natural-world-06-s0"
  },
  {
    "id": "food-culture-01",
    "chapterId": "food-culture",
    "difficulty": "easy",
    "categoryIds": [
      "fruit",
      "dessert",
      "festival"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "fruit": 4,
      "dessert": 5,
      "festival": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "food-culture-01-s0"
  },
  {
    "id": "food-culture-02",
    "chapterId": "food-culture",
    "difficulty": "easy",
    "categoryIds": [
      "festival",
      "drink",
      "fruit"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "festival": 3,
      "drink": 4,
      "fruit": 5
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "food-culture-02-s0"
  },
  {
    "id": "food-culture-03",
    "chapterId": "food-culture",
    "difficulty": "normal",
    "categoryIds": [
      "drink",
      "cuisine",
      "dessert",
      "festival"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "drink": 6,
      "cuisine": 6,
      "dessert": 4,
      "festival": 4
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "food-culture-03-s0"
  },
  {
    "id": "food-culture-04",
    "chapterId": "food-culture",
    "difficulty": "normal",
    "categoryIds": [
      "dessert",
      "cuisine",
      "fruit",
      "drink"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "dessert": 6,
      "cuisine": 4,
      "fruit": 6,
      "drink": 4
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "food-culture-04-s0"
  },
  {
    "id": "food-culture-05",
    "chapterId": "food-culture",
    "difficulty": "hard",
    "categoryIds": [
      "cuisine",
      "dessert",
      "drink",
      "fruit",
      "festival"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "cuisine": 5,
      "dessert": 5,
      "drink": 7,
      "fruit": 7,
      "festival": 6
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "food-culture-05-s1"
  },
  {
    "id": "food-culture-06",
    "chapterId": "food-culture",
    "difficulty": "hard",
    "categoryIds": [
      "cuisine",
      "drink",
      "fruit",
      "dessert",
      "festival"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "cuisine": 5,
      "drink": 7,
      "fruit": 5,
      "dessert": 6,
      "festival": 7
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "food-culture-06-s4"
  },
  {
    "id": "world-travel-01",
    "chapterId": "world-travel",
    "difficulty": "easy",
    "categoryIds": [
      "country",
      "cuisine",
      "city"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "country": 4,
      "cuisine": 5,
      "city": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "world-travel-01-s0"
  },
  {
    "id": "world-travel-02",
    "chapterId": "world-travel",
    "difficulty": "easy",
    "categoryIds": [
      "occupation",
      "city",
      "cuisine"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "occupation": 5,
      "city": 4,
      "cuisine": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "world-travel-02-s0"
  },
  {
    "id": "world-travel-03",
    "chapterId": "world-travel",
    "difficulty": "normal",
    "categoryIds": [
      "city",
      "vehicle",
      "country",
      "cuisine"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "city": 6,
      "vehicle": 4,
      "country": 6,
      "cuisine": 4
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "world-travel-03-s0"
  },
  {
    "id": "world-travel-04",
    "chapterId": "world-travel",
    "difficulty": "normal",
    "categoryIds": [
      "occupation",
      "city",
      "cuisine",
      "country"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "occupation": 6,
      "city": 4,
      "cuisine": 4,
      "country": 6
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "world-travel-04-s0"
  },
  {
    "id": "world-travel-05",
    "chapterId": "world-travel",
    "difficulty": "hard",
    "categoryIds": [
      "cuisine",
      "vehicle",
      "country",
      "city",
      "occupation"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "cuisine": 5,
      "vehicle": 6,
      "country": 7,
      "city": 5,
      "occupation": 7
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "world-travel-05-s2"
  },
  {
    "id": "world-travel-06",
    "chapterId": "world-travel",
    "difficulty": "hard",
    "categoryIds": [
      "cuisine",
      "occupation",
      "sport",
      "city",
      "vehicle"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "cuisine": 5,
      "occupation": 7,
      "sport": 6,
      "city": 7,
      "vehicle": 5
    },
    "targetThreeStarMoves": 53,
    "targetTwoStarMoves": 63,
    "targetThreeStarTime": 235,
    "targetTwoStarTime": 350,
    "seed": "world-travel-06-s1"
  },
  {
    "id": "arts-entertainment-01",
    "chapterId": "arts-entertainment",
    "difficulty": "easy",
    "categoryIds": [
      "architecture",
      "musicGenre",
      "filmGenre"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "architecture": 5,
      "musicGenre": 4,
      "filmGenre": 3
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "arts-entertainment-01-s0"
  },
  {
    "id": "arts-entertainment-02",
    "chapterId": "arts-entertainment",
    "difficulty": "easy",
    "categoryIds": [
      "instrument",
      "architecture",
      "musicGenre"
    ],
    "columnCount": 4,
    "categorySlotCount": 2,
    "deckEnabled": false,
    "deckSize": 0,
    "categoryWordCounts": {
      "instrument": 5,
      "architecture": 3,
      "musicGenre": 4
    },
    "targetThreeStarMoves": 23,
    "targetTwoStarMoves": 27,
    "targetThreeStarTime": 101,
    "targetTwoStarTime": 150,
    "seed": "arts-entertainment-02-s0"
  },
  {
    "id": "arts-entertainment-03",
    "chapterId": "arts-entertainment",
    "difficulty": "normal",
    "categoryIds": [
      "filmGenre",
      "instrument",
      "musicGenre",
      "architecture"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "filmGenre": 6,
      "instrument": 6,
      "musicGenre": 4,
      "architecture": 4
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "arts-entertainment-03-s0"
  },
  {
    "id": "arts-entertainment-04",
    "chapterId": "arts-entertainment",
    "difficulty": "normal",
    "categoryIds": [
      "filmGenre",
      "instrument",
      "architecture",
      "musicGenre"
    ],
    "columnCount": 5,
    "categorySlotCount": 2,
    "deckEnabled": true,
    "deckSize": 7,
    "categoryWordCounts": {
      "filmGenre": 6,
      "instrument": 4,
      "architecture": 4,
      "musicGenre": 6
    },
    "targetThreeStarMoves": 36,
    "targetTwoStarMoves": 43,
    "targetThreeStarTime": 161,
    "targetTwoStarTime": 240,
    "seed": "arts-entertainment-04-s0"
  },
  {
    "id": "arts-entertainment-05",
    "chapterId": "arts-entertainment",
    "difficulty": "hard",
    "categoryIds": [
      "filmGenre",
      "musicGenre",
      "architecture",
      "instrument"
    ],
    "columnCount": 6,
    "categorySlotCount": 3,
    "deckEnabled": true,
    "deckSize": 9,
    "categoryWordCounts": {
      "filmGenre": 7,
      "musicGenre": 7,
      "architecture": 5,
      "instrument": 5
    },
    "targetThreeStarMoves": 42,
    "targetTwoStarMoves": 50,
    "targetThreeStarTime": 188,
    "targetTwoStarTime": 280,
    "seed": "arts-entertainment-05-s0"
  }
]
